apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    minReadySeconds: 3
    revisionHistoryLimit: 5
    progressDeadlineSeconds: 60
    strategy:
        rollingUpdate:
            maxUnavailable: 0
        type: RollingUpdate
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "9090"
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: ghcr.io/stefanprodan/podinfo:6.3.3
                  imagePullPolicy: IfNotPresent
                  ports:
                    - name: http
                      containerPort: 9898
                      protocol: TCP
                    - name: http-metrics
                      containerPort: 9797
                      protocol: TCP
                    - name: grpc
                      containerPort: 9999
                      protocol: TCP
                  command:
                    - ./podinfo
                    - --port=9898
                    - --port-metrics=9797
                    - --grpc-port=9999
                    - --grpc-service-name=backend
                    - --level=info
                    - --cache-server=cache:6379
                  env:
                    - name: PODINFO_UI_COLOR
                      value: '#34577c'
                  livenessProbe:
                    exec:
                        command:
                            - podcli
                            - check
                            - http
                            - localhost:9898/healthz
                    initialDelaySeconds: 5
                    timeoutSeconds: 5
                  readinessProbe:
                    exec:
                        command:
                            - podcli
                            - check
                            - http
                            - localhost:9898/readyz
                    initialDelaySeconds: 5
                    timeoutSeconds: 5
                  resources:
                    limits:
                        cpu: 2000m
                        memory: 512Mi
                    requests:
                        cpu: 100m
                        memory: 32Mi
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OgNSosAGaG35mUUd,iv:xpUYpaUTmIKJNx74E4czrxhF3hzD8IsHVZ0YrhCDCnw=,tag:7E2ZFQU/HpbBd36hwXEgOg==,type:str]
    username: cHJvZHVzZXI=
kind: Secret
metadata:
    name: prod-db-secret
    namespace: podinfo
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-15T10:34:44Z"
    mac: ENC[AES256_GCM,data:q/cJBNhTa4SpsI062Cn7x0Sxuur+LW6wFtVPETWwK5K8HCEWHFXcYiOyN5XmP/R281hfHzbO3lr8Dvp/AUw9W2gBIJqVTxkaEbTCckmaCze3oHrqBBWuXoyr4mDMetW4z6CpYQghJVXWgi0xeGjguWAZDY0dS6YnPEWmKRYIns4=,iv:rtydbhUPjK1z5KaY5Ck3eMSwZSpFXZ+Ov7tSL8Le6ck=,tag:GpqHHIMqg0zEO6cwmv5TKA==,type:str]
    pgp:
        - created_at: "2023-02-15T10:34:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA1ho3yLJmNgCAQwApE6UCzeege2lK7kdUHwPLurlUiuhtQAohRXnDVmmGvYg
            zBVuntq393mC2MwMgQ0VH3Lg8cqbwR7jNfwddgFctDCkB43jcq++zeBqvBI1UBuA
            KtG8tHqqGPyN0juYxBV7THiAtFN9Ns838jTyyh4/TepZbcShEfdtadHeNkRu4nG3
            Y3DDdnqbGpOY08MsN4KSHtLwGoR18tLjOyjqt5leislwXVmKRMQEYmNuCCUoP/QG
            JnMRJd4pd4wb7gOgzOlQAs81j0QRHhhKwAafoyayUFr0rGGlbs+Kq5hzlhabdZUK
            KjutMTFHn8oc3VdVVd86j0ALWzPMsSwLVcw16EmHOhX5J63Y2f+BunvFJ78K7V4n
            +8diKWefKbjmzfKAhn6+Eo7ewRIIhSMMg4Oj9I1xmoWSbaEVFO7rDiqHqJ56tEMi
            f9yy1eJdNwx7SQhX5xBV3lqHKc3nZfo1UjDWN6IG8TiiLMk+jpqSIkLvJARs2aQR
            C/VdVU59fWlcbGuZ34Pk1GgBCQIQkJbuzzHQMABqdKiFSfVUgzJEKF0qQG9P/ieI
            VKw+ULwiiMs1pMwKFAn08eOjVT2Nwi/6zXZVx3bh6or0n8ttxHFgeZ5cNs3BUt4Y
            bxd/skuTT2Tz6MOMrs8dpYlg+67Vg3JJ5g==
            =czVe
            -----END PGP MESSAGE-----
          fp: 4BAA608D1B33192981387D8245CA0A4E3DD1C552
    encrypted_regex: password
    version: 3.7.3
