apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    minReadySeconds: 3
    revisionHistoryLimit: 5
    progressDeadlineSeconds: 60
    strategy:
        rollingUpdate:
            maxUnavailable: 0
        type: RollingUpdate
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: ENC[AES256_GCM,data:xF6vyw==,iv:ifpS8Uk65EN5Oss+gDPcC8JRKppuWahb2t51YyEVU5Y=,tag:MA3/rODOncKMXy113J9w9g==,type:str]
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: ghcr.io/stefanprodan/podinfo:6.3.3
                  imagePullPolicy: IfNotPresent
                  ports:
                    - name: http
                      containerPort: 9898
                      protocol: TCP
                    - name: http-metrics
                      containerPort: 9797
                      protocol: TCP
                    - name: grpc
                      containerPort: 9999
                      protocol: TCP
                  command:
                    - ./podinfo
                    - --port=9898
                    - --port-metrics=9797
                    - --grpc-port=9999
                    - --grpc-service-name=backend
                    - --level=info
                    - --cache-server=cache:6379
                  env:
                    - name: PODINFO_UI_COLOR
                      value: '#34577c'
                  livenessProbe:
                    exec:
                        command:
                            - podcli
                            - check
                            - http
                            - localhost:9898/healthz
                    initialDelaySeconds: 5
                    timeoutSeconds: 5
                  readinessProbe:
                    exec:
                        command:
                            - podcli
                            - check
                            - http
                            - localhost:9898/readyz
                    initialDelaySeconds: 5
                    timeoutSeconds: 5
                  resources:
                    limits:
                        cpu: 2000m
                        memory: 512Mi
                    requests:
                        cpu: 100m
                        memory: 32Mi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-15T10:17:07Z"
    mac: ENC[AES256_GCM,data:DJIeSfHmb8klpyhkHSyqTtqR+SmlgFfr49wC4pugsCdaJdXN8lU5rngJwBBoB/P3GZLXA9QfrZzynujPdNpBH1p1pTi8TO69WFUOn9pDjTgVY0MV1Ilm1d7wRfpVq2ZQHrTZ92SkTZ1hzW/hq3PS4ErrsUN2hpJs0sP926OVuWs=,iv:HXdRKfPcdI2wmUSYaCjGGaZQZGwsiMhPlBDye/XlXxs=,tag:hQUw9HrV9dAYm9IK3U5xKw==,type:str]
    pgp:
        - created_at: "2023-02-15T10:17:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA1ho3yLJmNgCAQwA3jbNXTgqHlZkVdLfrIiexocNzMsRGwxfyF31h1+Ah7iD
            K9gJqakgf3cm5wu9qgaN83cPjHKLlpwa5Oc4YWxjJ2ZhsXcH5CqtboCV8rxtLByZ
            Df+/G0weAFaWngJUShEE/LvNVz5jSU+b5jKGUC5kBeAkcOwcIww6vqKub4X1+vB1
            Tp4FGaILdyc8MW1I2rKiZFm/e2x1HGyyvXOUcAQjmuIDZjvMJmfJ4W1TVvR3LslM
            jDnSIdeDvrtz24xV+Bp9tGtu4DQExZEuDGS26I2xwslM+EPU8RP+fSPinypU0/nE
            NqqCW+JGVl3ic8EIIF3ma6myb0JVI95DG38rPp3boDlqA5+689LcK9h3Oy+MtAzb
            i9PFb8GIi5TZwN5rBLGVPj90OCEDAu9zFRDqAzFuQb+JShFrQbt3GFuWFd6MoIDH
            3B5eT3/VqOk3IYxVFUELPSsoycvWKd2xXZSz0UnaYdDYh4lEqyysi0moViIgcV2a
            HxJ6y90q5a7iM3JLbEwC1GgBCQIQJR/+Nd7yAzzAC98fumIWPoOqdemGgL53MqrQ
            vS6prlFzX9GurbyYqCYzAHumbYGa9RXP4tC22E4oAuLDgx3WdHV0IZgP6W7KQbZW
            9Zf3S9aBWOaZWjubrgs+467ZQBMdvAo3vA==
            =4eX0
            -----END PGP MESSAGE-----
          fp: 4BAA608D1B33192981387D8245CA0A4E3DD1C552
    encrypted_regex: prometheus.io\/port
    version: 3.7.3
